name: CD with Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Environment
      run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV && echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Pull the Docker image
      run: docker pull kirathefirst/appflask:latest

    - name: Stop and remove existing Docker container (if exists)
      run: |
        docker stop appflask-container || true
        docker rm appflask-container || true

    - name: Run Docker container
      run: |
        docker run -d --name appflask-container -p 80:80 kirathefirst/appflask:latest

